import DimensionCard from './DimensionCard';
import { type EvaluationResponse } from '../services/api';

interface EvaluationResultsProps {
  evaluation: EvaluationResponse;
}

export default function EvaluationResults({ evaluation }: EvaluationResultsProps) {
  return (
    <section className="space-y-6 rounded-3xl border border-white/10 bg-slate-900/80 p-6 shadow-xl shadow-black/20">
      {evaluation.dimensions.correctness.warnings.length > 0 || evaluation.dimensions.reasoning.weaknesses.length > 0 ? (
        <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-sm text-amber-200">
          <strong className="block">Polish warning:</strong>
          <span className="block">This output contains flags (warnings or weak reasoning). Inspect traces before exporting.</span>
        </div>
      ) : null}
      <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="text-sm uppercase tracking-[0.24em] text-slate-400">Evaluation workspace</p>
          <h2 className="mt-2 text-2xl font-semibold text-white">Review the AI output across five dimensions</h2>
          <p className="mt-2 text-sm text-slate-400">
            Each section is generated by the Calibrate engine and linked to a trace for auditability.
          </p>
        </div>
        <div className="flex flex-wrap gap-3 text-sm">
          <span className="rounded-2xl bg-white/5 px-3 py-2 text-slate-300">ID: {evaluation.evaluation_id.slice(0, 8)}</span>
          <span className="rounded-2xl bg-white/5 px-3 py-2 text-slate-300">Model: {evaluation.model}</span>
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <DimensionCard
          title="Correctness"
          subtitle="Claims & unsupported statements"
          items={[...evaluation.dimensions.correctness.claims, ...evaluation.dimensions.correctness.warnings]}
          accent="text-emerald-300"
        />
        <DimensionCard
          title="Completeness"
          subtitle="Missing context or gaps"
          items={[...evaluation.dimensions.completeness.gaps, ...evaluation.dimensions.completeness.risks]}
          accent="text-sky-300"
        />
        <DimensionCard
          title="Reasoning"
          subtitle="Logical flow and weak links"
          items={[...evaluation.dimensions.reasoning.steps, ...evaluation.dimensions.reasoning.weaknesses]}
          accent="text-violet-300"
        />
        <DimensionCard
          title="Usefulness"
          subtitle="Actionability and intent alignment"
          items={[`${evaluation.dimensions.usefulness.alignment.toUpperCase()} alignment`, evaluation.dimensions.usefulness.rationale]}
          accent="text-amber-300"
        />
        <DimensionCard
          title="Uncertainty"
          subtitle="Assumptions and unknowns"
          items={evaluation.dimensions.uncertainty.items}
          accent="text-rose-300"
        />
      </div>

      <div className="rounded-3xl border border-white/10 bg-slate-950/80 p-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm uppercase tracking-[0.24em] text-slate-400">Verdict gate</p>
            <h3 className="mt-2 text-xl font-semibold text-white">Review, decide, then export</h3>
          </div>
          <div className="rounded-2xl bg-slate-800 px-4 py-2 text-sm text-slate-300">
            Traces: {evaluation.trace_ids.length}
          </div>
        </div>
        <p className="mt-4 text-sm leading-6 text-slate-400">
          The Calibrate UI surfaces each dimension in a review-first layout. Use the trace IDs above to inspect the source prompts and responses for every signal.
        </p>
      </div>
    </section>
  );
}
